//! The `AnimusCluster` validating admission webhook (S-07e, ADR 0070) — a
//! second, opt-in HTTPS listener in the same `animus-operator` binary,
//! entirely separate from the reconcile loop in [`crate::controller`].
//!
//! **Fast and side-effect free, by design.** The handler in this module
//! does exactly one thing: decode the incoming `AdmissionReview`, run
//! [`crate::validate::validate_spec`] (a pure function, no cluster access)
//! against the new spec (and the old one, for an UPDATE), and answer
//! allowed/denied. It never calls the Kubernetes API, never talks to a
//! pod's admin port, and never blocks on anything but decoding the request
//! body — a webhook the API server calls synchronously on every write, with
//! `failurePolicy: Fail` (`deploy/operator/webhook.yaml`), turns any slower
//! or less reliable behavior directly into cluster-wide write unavailability.
//! The live checks this crate also performs (does a referenced `Secret`
//! actually exist — `crate::controller::validate_encryption_key_secret`)
//! stay reconciler-only for exactly this reason; see `crate::validate`'s own
//! module doc.
//!
//! **Why a plain `hyper` server, not `kube`'s own webhook helpers.** `kube`
//! ships the `AdmissionReview`/`AdmissionRequest`/`AdmissionResponse` types
//! (the `admission` Cargo feature, enabled in this crate's `Cargo.toml`) but
//! no server runtime of its own — an admission webhook is an ordinary HTTPS
//! endpoint the API server POSTs to, and this crate already has the
//! `hyper`/`hyper-util`/`tokio-rustls` stack in its dependency graph for the
//! admin-port client (`admin_client.rs`) and the reconciler's own TLS
//! reading. This module is the mirror image of that client: a server-only
//! TLS acceptor (no client certificate — the API server verifies this
//! webhook's cert via `caBundle`/`inject-ca-from`, but this webhook itself
//! never verifies who's calling, matching the admin port's own no-auth
//! posture, ADR 0020) wrapping the identical `hyper::server::conn::http1`
//! plus `hyper_util::rt::TokioIo` shape `crates/animusd/src/admin.rs::serve`
//! uses for its own accept loop, one real Kubernetes API server call away.
//!
//! **Kubernetes requires TLS for a webhook** — there is no plain-HTTP
//! admission webhook shape at all, unlike the admin port's own optional TLS
//! (ADR 0064). `--webhook-cert`/`--webhook-key` (`main.rs`) are therefore
//! not "TLS if you want it," they are simply "the webhook's own cert/key" —
//! see this crate's own `deploy/operator/README.md` section for the two
//! supported ways to obtain them (a cert-manager `Certificate`, generated by
//! `animus-operator webhook-cert` and applied once; or a hand-issued
//! `kubernetes.io/tls` `Secret` mounted the same way).

use std::convert::Infallible;
use std::net::SocketAddr;
use std::path::Path;
use std::sync::Arc;

use bytes::Bytes;
use http_body_util::{BodyExt, Full};
use hyper::body::Incoming;
use hyper::service::service_fn;
use hyper::{Method, Request, Response, StatusCode};
use hyper_util::rt::TokioIo;
use kube::core::DynamicObject;
use kube::core::admission::{AdmissionRequest, AdmissionResponse, AdmissionReview};
use rustls_pki_types::pem::PemObject;
use tokio::net::TcpListener;
use tokio_rustls::TlsAcceptor;

use crate::crd::AnimusCluster;
use crate::validate;

/// The one path the `ValidatingWebhookConfiguration` (`deploy/operator/
/// webhook.yaml`) points its `clientConfig.service.path` at.
pub const VALIDATE_PATH: &str = "/validate";

/// The `AnimusCluster` kind name this webhook expects `AdmissionRequest::
/// kind.kind` to carry — a `ValidatingWebhookConfiguration` correctly
/// scoped to `animusdb.io`/`animusclusters` should never send anything
/// else, but [`handle_review`] checks it explicitly anyway (defense in
/// depth against a misconfigured webhook registration) rather than relying
/// solely on a decode failure to catch the mismatch.
const EXPECTED_KIND: &str = "AnimusCluster";

/// Anything that stops the webhook server from starting at all — a bad
/// cert/key pair, or a port already in use. Once started, a per-request
/// failure (a malformed body, a resource-kind mismatch) is answered as a
/// denial, never as a process error — see [`handle_review`].
#[derive(Debug, thiserror::Error)]
pub enum WebhookError {
    #[error("loading TLS material: {0}")]
    Tls(String),
    #[error("binding webhook listener on {addr}: {source}")]
    Bind {
        addr: SocketAddr,
        #[source]
        source: std::io::Error,
    },
}

/// Build a server-only (no client certificate requested) `tokio_rustls::
/// TlsAcceptor` from a PEM cert chain + private key file pair — the
/// server-side mirror of `admin_client.rs::build_tls_connector`. Assumes a
/// process-global rustls `CryptoProvider` is already installed
/// (`main.rs::run` installs `ring` before this is ever called).
pub fn load_tls_acceptor(cert_path: &Path, key_path: &Path) -> Result<TlsAcceptor, WebhookError> {
    // Read the raw bytes ourselves and parse via `*_slice_iter`/
    // `from_pem_slice` (not `rustls_pki_types`'s own `*_file` helpers) —
    // this workspace's dependency graph enables `rustls-pki-types`'
    // `alloc` feature but not `std` (`admin_client.rs::build_tls_connector`
    // makes the identical choice, for the identical reason), and the
    // slice-based methods work either way.
    let cert_bytes = std::fs::read(cert_path)
        .map_err(|e| WebhookError::Tls(format!("reading cert file {cert_path:?}: {e}")))?;
    let key_bytes = std::fs::read(key_path)
        .map_err(|e| WebhookError::Tls(format!("reading key file {key_path:?}: {e}")))?;
    let certs = rustls_pki_types::CertificateDer::pem_slice_iter(&cert_bytes)
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| WebhookError::Tls(format!("parsing cert file {cert_path:?}: {e}")))?;
    if certs.is_empty() {
        return Err(WebhookError::Tls(format!(
            "no certificates found in {cert_path:?}"
        )));
    }
    let key = rustls_pki_types::PrivateKeyDer::from_pem_slice(&key_bytes)
        .map_err(|e| WebhookError::Tls(format!("parsing key file {key_path:?}: {e}")))?;

    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ServerConfig::builder_with_provider(provider)
        .with_protocol_versions(rustls::ALL_VERSIONS)
        .map_err(|e| WebhookError::Tls(format!("selecting TLS protocol versions: {e}")))?
        .with_no_client_auth()
        .with_single_cert(certs, key)
        .map_err(|e| WebhookError::Tls(format!("building TLS server config: {e}")))?;
    Ok(TlsAcceptor::from(Arc::new(config)))
}

/// Run the decoded [`AdmissionReview<AnimusCluster>`] through
/// [`validate::validate_spec`] and build the matching response, wrapped
/// back into a generic [`AdmissionReview<DynamicObject>`] — `kube::core::
/// admission::AdmissionResponse::into_review`'s own return type, since a
/// response carries no typed object, only the (possibly denied) verdict.
///
/// Exposed as a standalone function, over the *decoded* request, precisely
/// so the handler tests below need no socket at all — this is the entire
/// interesting logic of the webhook; `handle_request` (below) is just the
/// HTTP/JSON plumbing around it.
#[must_use]
pub fn handle_review(review: AdmissionReview<AnimusCluster>) -> AdmissionReview<DynamicObject> {
    let request: AdmissionRequest<AnimusCluster> = match review.try_into() {
        Ok(req) => req,
        Err(_) => {
            return AdmissionResponse::invalid(
                "AdmissionReview carried no request (a webhook response body \
                 sent as a request?)",
            )
            .into_review();
        }
    };

    if request.kind.kind != EXPECTED_KIND {
        return AdmissionResponse::from(&request)
            .deny(format!(
                "this webhook only validates {EXPECTED_KIND} — received {:?} \
                 (check the ValidatingWebhookConfiguration's own rules)",
                request.kind.kind
            ))
            .into_review();
    }

    // DELETE carries no `object` to validate — nothing for this webhook to
    // say (the `ValidatingWebhookConfiguration` only registers CREATE/
    // UPDATE anyway, so this is unreachable in production, not a case this
    // webhook is actually asked to police).
    let Some(new) = &request.object else {
        return AdmissionResponse::from(&request).into_review();
    };

    let old = request.old_object.as_ref().map(|o| &o.spec);
    match validate::validate_spec(old, &new.spec) {
        Ok(()) => AdmissionResponse::from(&request).into_review(),
        Err(violations) => {
            let message = violations
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("; ");
            AdmissionResponse::from(&request)
                .deny(message)
                .into_review()
        }
    }
}

fn json_response(
    status: StatusCode,
    body: &AdmissionReview<DynamicObject>,
) -> Response<Full<Bytes>> {
    let bytes = serde_json::to_vec(body).unwrap_or_else(|_| b"{}".to_vec());
    Response::builder()
        .status(status)
        .header("content-type", "application/json")
        .body(Full::new(Bytes::from(bytes)))
        .expect("a fixed set of well-formed headers over a JSON body always builds")
}

/// The `hyper` request handler: only `POST /validate` is meaningful — a
/// method/path mismatch is `404`, never reachable in production since the
/// `ValidatingWebhookConfiguration` only ever posts to
/// [`VALIDATE_PATH`] — everything else always answers `200` with a JSON
/// `AdmissionReview` body (Kubernetes' own contract: an admission webhook's
/// verdict rides the response *body*, not the HTTP status; a malformed
/// request body still gets a `200` carrying a denial via
/// `AdmissionResponse::invalid`, matching `kube::core::admission`'s own
/// documented usage).
async fn handle_request(req: Request<Incoming>) -> Result<Response<Full<Bytes>>, Infallible> {
    if req.method() != Method::POST || req.uri().path() != VALIDATE_PATH {
        return Ok(Response::builder()
            .status(StatusCode::NOT_FOUND)
            .body(Full::new(Bytes::new()))
            .expect("a fixed empty 404 body always builds"));
    }

    let body = match req.into_body().collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(e) => {
            return Ok(json_response(
                StatusCode::OK,
                &AdmissionResponse::invalid(format!("reading request body: {e}")).into_review(),
            ));
        }
    };

    let review: AdmissionReview<AnimusCluster> = match serde_json::from_slice(&body) {
        Ok(r) => r,
        Err(e) => {
            return Ok(json_response(
                StatusCode::OK,
                &AdmissionResponse::invalid(format!("malformed AdmissionReview: {e}"))
                    .into_review(),
            ));
        }
    };

    Ok(json_response(StatusCode::OK, &handle_review(review)))
}

/// Serve the webhook forever on `addr`, TLS-terminated by `acceptor`. Never
/// returns on success (mirrors `crates/animusd/src/admin.rs::serve`'s own
/// accept-loop contract); returns [`WebhookError::Bind`] only if the
/// listener itself can't bind.
///
/// One task per connection, matching `admin.rs::serve`'s own shape — a
/// failed TLS handshake or a connection-serving error is logged and the
/// loop keeps accepting every other connection; nothing here can bring the
/// whole webhook down over one bad peer.
pub async fn run(addr: SocketAddr, acceptor: TlsAcceptor) -> Result<(), WebhookError> {
    let listener = TcpListener::bind(addr)
        .await
        .map_err(|source| WebhookError::Bind { addr, source })?;
    tracing::info!(%addr, "admission webhook listening");
    loop {
        let (stream, peer) = match listener.accept().await {
            Ok(pair) => pair,
            Err(e) => {
                tracing::warn!(error = %e, "webhook accept failed");
                continue;
            }
        };
        let acceptor = acceptor.clone();
        // ADR 0003 / ADR 0061 Decision 4 (rung B5): this crate has no `Env`
        // seam (`crates/animus-operator/CLAUDE.md`'s own note) — a real
        // Kubernetes API server dialing a real socket is outside ADR 0003's
        // determinism scope, the identical allowance every other real-socket
        // accept loop in this crate (`admin_client.rs`'s own request
        // timeout) already carries.
        #[allow(
            clippy::disallowed_methods,
            reason = "animus-operator has no Env seam (see its own CLAUDE.md); the webhook's accept loop is a real Kubernetes API server dialing a real socket, outside ADR 0003's scope"
        )]
        tokio::spawn(async move {
            let tls_stream = match acceptor.accept(stream).await {
                Ok(s) => s,
                Err(e) => {
                    tracing::warn!(error = %e, %peer, "webhook TLS handshake failed");
                    return;
                }
            };
            let io = TokioIo::new(tls_stream);
            if let Err(e) = hyper::server::conn::http1::Builder::new()
                .serve_connection(io, service_fn(handle_request))
                .await
            {
                tracing::debug!(error = %e, %peer, "webhook connection closed");
            }
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crd::AnimusClusterSpec;
    use crate::desired::test_support::test_cluster;
    use k8s_openapi::api::authentication::v1::UserInfo;
    use kube::core::admission::Operation;
    use kube::core::{GroupVersionKind, GroupVersionResource, TypeMeta};

    fn spec(nodes: i32, control_nodes: Option<i32>) -> AnimusClusterSpec {
        AnimusClusterSpec {
            nodes,
            control_nodes,
            ..Default::default()
        }
    }

    /// A minimal `AnimusCluster` carrying `spec`, reusing the same fixture
    /// every `desired::*` builder test already shares.
    fn cluster(spec: AnimusClusterSpec) -> AnimusCluster {
        let mut cluster = test_cluster("demo", "ns1", spec.nodes, spec.control_nodes);
        cluster.spec = spec;
        cluster
    }

    fn animuscluster_gvk() -> GroupVersionKind {
        GroupVersionKind {
            group: "animusdb.io".to_string(),
            version: "v1alpha1".to_string(),
            kind: "AnimusCluster".to_string(),
        }
    }

    fn animuscluster_gvr() -> GroupVersionResource {
        GroupVersionResource::gvr("animusdb.io", "v1alpha1", "animusclusters")
    }

    fn review(
        operation: Operation,
        object: Option<AnimusCluster>,
        old_object: Option<AnimusCluster>,
        kind: GroupVersionKind,
    ) -> AdmissionReview<AnimusCluster> {
        AdmissionReview {
            types: TypeMeta {
                api_version: "admission.k8s.io/v1".to_string(),
                kind: "AdmissionReview".to_string(),
            },
            request: Some(AdmissionRequest {
                types: TypeMeta {
                    api_version: "admission.k8s.io/v1".to_string(),
                    kind: "AdmissionReview".to_string(),
                },
                uid: "test-uid".to_string(),
                kind,
                resource: animuscluster_gvr(),
                sub_resource: None,
                request_kind: None,
                request_resource: None,
                request_sub_resource: None,
                name: "demo".to_string(),
                namespace: Some("ns1".to_string()),
                operation,
                user_info: UserInfo::default(),
                object,
                old_object,
                dry_run: false,
                options: None,
            }),
            response: None,
        }
    }

    #[test]
    fn a_valid_create_is_allowed() {
        let out = handle_review(review(
            Operation::Create,
            Some(cluster(spec(3, None))),
            None,
            animuscluster_gvk(),
        ));
        let resp = out.response.expect("response set");
        assert!(resp.allowed, "{:?}", resp.result);
        assert_eq!(resp.uid, "test-uid");
    }

    #[test]
    fn an_invalid_create_is_denied_naming_the_bad_field() {
        let mut bad = spec(3, None);
        bad.tls = Some(crate::crd::TlsSpec {
            secret_name: None,
            cert_manager: None,
        });
        let out = handle_review(review(
            Operation::Create,
            Some(cluster(bad)),
            None,
            animuscluster_gvk(),
        ));
        let resp = out.response.expect("response set");
        assert!(!resp.allowed);
        assert!(
            resp.result.message.contains("spec.tls"),
            "{}",
            resp.result.message
        );
        assert_eq!(resp.uid, "test-uid");
    }

    #[test]
    fn an_invalid_update_shrinking_control_nodes_is_denied() {
        let old = cluster(spec(5, Some(3)));
        let new = cluster(spec(5, Some(2)));
        let out = handle_review(review(
            Operation::Update,
            Some(new),
            Some(old),
            animuscluster_gvk(),
        ));
        let resp = out.response.expect("response set");
        assert!(!resp.allowed);
        assert!(
            resp.result.message.contains("spec.controlNodes"),
            "{}",
            resp.result.message
        );
    }

    #[test]
    fn a_valid_update_growing_control_nodes_is_allowed() {
        let old = cluster(spec(5, Some(3)));
        let new = cluster(spec(5, Some(4)));
        let out = handle_review(review(
            Operation::Update,
            Some(new),
            Some(old),
            animuscluster_gvk(),
        ));
        let resp = out.response.expect("response set");
        assert!(resp.allowed, "{:?}", resp.result);
    }

    #[test]
    fn a_malformed_body_is_denied_not_a_process_error() {
        let out: AdmissionReview<DynamicObject> =
            match serde_json::from_str::<AdmissionReview<AnimusCluster>>("{ not json") {
                Ok(r) => handle_review(r),
                Err(e) => AdmissionResponse::invalid(format!("malformed AdmissionReview: {e}"))
                    .into_review(),
            };
        let resp = out.response.expect("response set");
        assert!(!resp.allowed);
    }

    #[test]
    fn a_review_with_no_request_is_invalid() {
        let review: AdmissionReview<AnimusCluster> = AdmissionReview {
            types: TypeMeta {
                api_version: "admission.k8s.io/v1".to_string(),
                kind: "AdmissionReview".to_string(),
            },
            request: None,
            response: None,
        };
        let out = handle_review(review);
        let resp = out.response.expect("response set");
        assert!(!resp.allowed);
    }

    #[test]
    fn an_unexpected_resource_kind_is_denied() {
        let wrong_kind = GroupVersionKind {
            group: "".to_string(),
            version: "v1".to_string(),
            kind: "Pod".to_string(),
        };
        let out = handle_review(review(
            Operation::Create,
            Some(cluster(spec(3, None))),
            None,
            wrong_kind,
        ));
        let resp = out.response.expect("response set");
        assert!(!resp.allowed);
        assert!(
            resp.result.message.contains("Pod"),
            "{}",
            resp.result.message
        );
    }

    #[test]
    fn a_delete_with_no_object_is_allowed() {
        let out = handle_review(review(Operation::Delete, None, None, animuscluster_gvk()));
        let resp = out.response.expect("response set");
        assert!(resp.allowed);
    }

    // --- Real-socket smoke test: a genuine HTTPS POST decoded end to end ---

    #[allow(
        clippy::disallowed_methods,
        reason = "animus-operator has no Env seam (see its own CLAUDE.md); a real-socket TLS smoke test is outside ADR 0003's scope"
    )]
    fn self_signed_cert(tmp: &std::path::Path) -> (std::path::PathBuf, std::path::PathBuf) {
        let cert = rcgen::generate_simple_self_signed(vec!["localhost".to_string()])
            .expect("self-signed cert generation");
        let cert_path = tmp.join("webhook.crt");
        let key_path = tmp.join("webhook.key");
        std::fs::write(&cert_path, cert.cert.pem()).expect("write cert");
        std::fs::write(&key_path, cert.key_pair.serialize_pem()).expect("write key");
        (cert_path, key_path)
    }

    #[tokio::test(flavor = "multi_thread")]
    async fn a_real_tls_post_is_decoded_and_an_invalid_spec_is_denied() {
        let tmp = std::env::temp_dir().join(format!(
            "animus-operator-webhook-test-{}",
            std::process::id()
        ));
        std::fs::create_dir_all(&tmp).expect("create temp dir");
        let (cert_path, key_path) = self_signed_cert(&tmp);

        // rustls needs a process-global CryptoProvider installed exactly
        // once; `main.rs::run` does this in production, so tests do it here
        // — `is_ok()`'d since a previous test in the same binary may have
        // already installed one (this crate's test binaries are one process
        // per `cargo test` invocation, so races are still possible across
        // `#[test]`s run in parallel, hence "install, ignore already-set").
        let _ = rustls::crypto::ring::default_provider().install_default();

        let acceptor =
            load_tls_acceptor(&cert_path, &key_path).expect("build TlsAcceptor from a fresh cert");

        let addr: SocketAddr = "127.0.0.1:0".parse().unwrap();
        let listener = tokio::net::TcpListener::bind(addr)
            .await
            .expect("bind ephemeral port");
        let bound_addr = listener.local_addr().unwrap();

        #[allow(
            clippy::disallowed_methods,
            reason = "animus-operator has no Env seam (see its own CLAUDE.md); a real-socket TLS smoke test is outside ADR 0003's scope"
        )]
        let server = tokio::spawn(async move {
            let (stream, _peer) = listener.accept().await.expect("accept one connection");
            let tls_stream = acceptor.accept(stream).await.expect("TLS handshake");
            let io = TokioIo::new(tls_stream);
            hyper::server::conn::http1::Builder::new()
                .serve_connection(io, service_fn(handle_request))
                .await
                .ok();
        });

        // A minimal, deliberately hand-rolled TLS client (this crate's own
        // `admin_client.rs::build_tls_connector` shape, trusting nothing —
        // a self-signed cert has no chain to verify against, so this test's
        // client skips verification entirely; production's real caller is
        // the Kubernetes API server, which verifies against `caBundle`, not
        // this test).
        let config = rustls::ClientConfig::builder()
            .dangerous()
            .with_custom_certificate_verifier(std::sync::Arc::new(NoVerify))
            .with_no_client_auth();
        let connector = tokio_rustls::TlsConnector::from(std::sync::Arc::new(config));
        let tcp = tokio::net::TcpStream::connect(bound_addr)
            .await
            .expect("connect to webhook listener");
        let server_name = rustls_pki_types::ServerName::try_from("localhost").unwrap();
        let mut tls = connector
            .connect(server_name, tcp)
            .await
            .expect("client TLS handshake");

        let mut bad = spec(3, None);
        bad.tls = Some(crate::crd::TlsSpec {
            secret_name: None,
            cert_manager: None,
        });
        let body = serde_json::to_vec(&review(
            Operation::Create,
            Some(cluster(bad)),
            None,
            animuscluster_gvk(),
        ))
        .unwrap();
        let request = format!(
            "POST {VALIDATE_PATH} HTTP/1.1\r\nHost: localhost\r\ncontent-type: application/json\r\ncontent-length: {}\r\nconnection: close\r\n\r\n",
            body.len()
        );
        use tokio::io::{AsyncReadExt, AsyncWriteExt};
        tls.write_all(request.as_bytes()).await.unwrap();
        tls.write_all(&body).await.unwrap();
        tls.flush().await.unwrap();

        let mut response = Vec::new();
        tls.read_to_end(&mut response).await.unwrap();
        server.await.unwrap();

        let response_text = String::from_utf8_lossy(&response);
        assert!(response_text.starts_with("HTTP/1.1 200"), "{response_text}");
        let body_start = response_text.find("\r\n\r\n").expect("header/body split") + 4;
        let review_out: AdmissionReview<DynamicObject> =
            serde_json::from_str(&response_text[body_start..]).expect("decode response body");
        let resp = review_out.response.expect("response set");
        assert!(!resp.allowed, "{:?}", resp.result);
        assert!(
            resp.result.message.contains("spec.tls"),
            "{}",
            resp.result.message
        );

        let _ = std::fs::remove_dir_all(&tmp);
    }

    /// A `rustls` certificate verifier that accepts anything — this test's
    /// client has no CA to verify a self-signed server cert against, and
    /// this test is proving the webhook's own request/response handling,
    /// not certificate-chain verification (which `rustls`/`webpki` already
    /// have their own, unrelated test coverage for).
    #[derive(Debug)]
    struct NoVerify;

    impl rustls::client::danger::ServerCertVerifier for NoVerify {
        fn verify_server_cert(
            &self,
            _end_entity: &rustls_pki_types::CertificateDer<'_>,
            _intermediates: &[rustls_pki_types::CertificateDer<'_>],
            _server_name: &rustls_pki_types::ServerName<'_>,
            _ocsp_response: &[u8],
            _now: rustls_pki_types::UnixTime,
        ) -> Result<rustls::client::danger::ServerCertVerified, rustls::Error> {
            Ok(rustls::client::danger::ServerCertVerified::assertion())
        }

        fn verify_tls12_signature(
            &self,
            _message: &[u8],
            _cert: &rustls_pki_types::CertificateDer<'_>,
            _dss: &rustls::DigitallySignedStruct,
        ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
            Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
        }

        fn verify_tls13_signature(
            &self,
            _message: &[u8],
            _cert: &rustls_pki_types::CertificateDer<'_>,
            _dss: &rustls::DigitallySignedStruct,
        ) -> Result<rustls::client::danger::HandshakeSignatureValid, rustls::Error> {
            Ok(rustls::client::danger::HandshakeSignatureValid::assertion())
        }

        fn supported_verify_schemes(&self) -> Vec<rustls::SignatureScheme> {
            vec![
                rustls::SignatureScheme::RSA_PKCS1_SHA256,
                rustls::SignatureScheme::ECDSA_NISTP256_SHA256,
                rustls::SignatureScheme::ED25519,
            ]
        }
    }
}
